/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerMenuPrincipal;


public class MenuPrincipal extends javax.swing.JFrame {

    private final ControllerMenuPrincipal controller;

    /**
     * Creates new form Cadastro
     */
    public MenuPrincipal() {
        initComponents();
        controller = new ControllerMenuPrincipal(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuMain = new javax.swing.JMenuBar();
        jMenuCadastrar = new javax.swing.JMenu();
        jCadastrarFormula = new javax.swing.JMenuItem();
        jCadastrarInsumos = new javax.swing.JMenuItem();
        jMenuConsultar = new javax.swing.JMenu();
        jConsultarFormulas = new javax.swing.JMenuItem();
        jConsultarCusto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setFocusTraversalPolicyProvider(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/bg.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        jMenuCadastrar.setText("Cadastrar");
        jMenuCadastrar.setToolTipText("");

        jCadastrarFormula.setText("Produto");
        jCadastrarFormula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarFormulaActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jCadastrarFormula);

        jCadastrarInsumos.setText("Insumos");
        jCadastrarInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarInsumosActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jCadastrarInsumos);

        jMenuMain.add(jMenuCadastrar);

        jMenuConsultar.setText("Consultar");
        jMenuConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultarActionPerformed(evt);
            }
        });

        jConsultarFormulas.setText("Produtos");
        jConsultarFormulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultarFormulasActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jConsultarFormulas);

        jConsultarCusto.setText("Custo de produção");
        jConsultarCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultarCustoActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jConsultarCusto);

        jMenuMain.add(jMenuConsultar);

        setJMenuBar(jMenuMain);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCadastrarFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarFormulaActionPerformed
        
        controller.opcCadProduto();
        
    }//GEN-LAST:event_jCadastrarFormulaActionPerformed

    private void jCadastrarInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarInsumosActionPerformed
        
        controller.opcCadInsumos();
        
    }//GEN-LAST:event_jCadastrarInsumosActionPerformed

    private void jMenuConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultarActionPerformed
        
    }//GEN-LAST:event_jMenuConsultarActionPerformed

    private void jConsultarFormulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultarFormulasActionPerformed
         controller.opcConsultProduto();
    }//GEN-LAST:event_jConsultarFormulasActionPerformed

    private void jConsultarCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultarCustoActionPerformed
        controller.opcConsultCusto();
    }//GEN-LAST:event_jConsultarCustoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jCadastrarFormula;
    private javax.swing.JMenuItem jCadastrarInsumos;
    private javax.swing.JMenuItem jConsultarCusto;
    private javax.swing.JMenuItem jConsultarFormulas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenu jMenuConsultar;
    private javax.swing.JMenuBar jMenuMain;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
